### ISSUE TITLE
Minesweeper Icons

### ISSUE THREAD

**Issue by gsalaman** [jlefkoff/GridBoard#12]
We've got minesweeper icons for "1", "2", and "3", but I think it's possible to have up to "8" (in a diabolical case).

May want to assign this to one of the "game design" members if any are interested in still creating icons...

Note...wasn't sure whether to flag this as a "bug" or "feature request"; chose "bug" as it's missing functionality.

**Comment by jlefkoff** [comment]
The highest theoretical number we need on an 8x8 grid is a 4. Which is a dark blue (see [here](https://i1.wp.com/www.crisgdwrites.com/wp-content/uploads/2016/06/minesweeper_tiles.jpg?fit=512%2C384))

**Comment by gsalaman** [comment]
What about this board situation, where x shows a bomb, and I'm using dashes for "no bomb around":
```
x x x 2 - - - -
x 8 x 3 - - - -
x x x 2 - - - -
2 3 2 1 - - - -
- - - - - - - - 
...
```
(yes, it's diabolical....)

And thought my way through the MS logic...it's actually not that bad.  May be a good excuse to run through "HLD/LLD"...

**Comment by jlefkoff** [comment]
That is technically correct, yes. What we should avoid is "hidden" bombs with no neighboring number as discussed in this [question](https://puzzling.stackexchange.com/questions/55021/in-minesweeper-does-every-bomb-have-to-have-at-least-one-neighboring-number)

**Comment by gsalaman** [comment]
Ah...okay.  That leads to the question:  "what are the requirements on our board?"  Sounds like we've got at least three:
* The 8x8 minesweeper board has 10 (TBR) bombs on it.
* Any given empty square can only be adjacent to at most 4 bombs (inferred from first answer above)
* No "hidden" bombs allowed.  Said another way, any given bomb must have at least one vacant square around it.

In any event, we're still missing the "4" png...

**Comment by gsalaman** [comment]
Added 4 and 5.  We'll respin the board if there are more than 5 touching a given square.
